#!/bin/bash
#PBS -N era5_check
#PBS -P k10
#PBS -q normal
#PBS -l ncpus=2
#PBS -l mem=16GB
#PBS -l walltime=00:30:00
#PBS -l storage=gdata/k10+scratch/nf33
#PBS -l jobfs=2GB
#PBS -j oe
#PBS -o /g/data/k10/zr7147/ERA5/PBL/era5_check_pbs.log

set -euo pipefail

source /g/data/k10/zr7147/miniconda3/etc/profile.d/conda.sh
conda activate /g/data/k10/zr7147/orcestra_env

/g/data/k10/zr7147/orcestra_env/bin/python \
    /home/565/zr7147/Proj/notebooks/era5_check.py
